app = "sapanjai"
primary_region = "sin"

[build]

[env]
  VOLUME_PATH = "/data"
  HF_HOME = "/data/hf-cache"  # Use HF_HOME instead of deprecated TRANSFORMERS_CACHE

[[mounts]]
  source = "data"
  destination = "/data"

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = "stop"
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[vm]]
  size = "performance-4x"
