# fly.toml app configuration file generated for sapanjai on 2025-07-29T21:25:19+07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'sapanjai'
primary_region = 'sin'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[build]

[env]

[[vm]]
  size = "a10"
